### ISSUE TITLE
I got error with EDR

### ISSUE THREAD

**Issue by amit-sec** [mertdas/SharpTerminator#1]
Loading driver from URL: https://github.com/mertdas/SharpTerminator/releases/download/terminate/Terminator.sys
Driver loaded successfully!
Service started successfully!
Waiting for 2000 milliseconds after starting the service...
Waiting for 2000 milliseconds after opening handle to driver...
Failed to register the process in the trusted list!

**Comment by mertdas** [comment]
Try to create service manually and execute SharpTerminator again:

sc create Terminator binPath= "C:\path\to\driver.sys" type= kernel start= demand

**Comment by amit-sec** [comment]
edr is removing sys driver , can we create service for remote location?

**Comment by mertdas** [comment]
No you can not
